site_name: "Aleksandr Lesnitsky - Portfolio"
site_author: "Aleksandr Lesnitsky"

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - Список работ: labs/index.md
    - Лаба 1: labs/lab1.md
  - Проекты: projects.md
  - Контакты: contact.md